# Reporter Markdown - gera um relatório Markdown pra comentários em PRs.

from __future__ import annotations

from pathlib import Path

from driftbrake.models import DiffResult, Severity

_SEVERITY_EMOJI = {
    Severity.BREAKING: "🔴",
    Severity.WARNING: "🟡",
    Severity.SAFE: "🟢",
}

_SEVERITY_LABEL = {
    Severity.BREAKING: "BREAKING",
    Severity.WARNING: "WARNING",
    Severity.SAFE: "SAFE",
}


class MarkdownReporter:
    # Gera um relatório de diff de schema em Markdown.

    def __init__(self, output_path: str | Path | None = None) -> None:
        self.output_path = Path(output_path) if output_path else None

    def render(self, result: DiffResult) -> str:
        # Renderiza o DiffResult como uma string Markdown.
        lines: list[str] = []

        lines.append("## Schema Change Report")
        lines.append("")
        lines.append(
            f"**Compared at:** {result.compared_at.strftime('%Y-%m-%d %H:%M:%S')}  "
        )
        lines.append(
            f"**Expected:** `{result.expected_source}`  "
            f"**Current:** `{result.current_source}`"
        )
        lines.append("")

        # Tabela de resumo
        lines.append("### Summary")
        lines.append("")
        lines.append("| Severity | Count |")
        lines.append("|----------|-------|")
        lines.append(f"| Breaking Changes | **{result.total_breaking}** |")
        lines.append(f"| Warnings | **{result.total_warnings}** |")
        lines.append(f"| Safe Changes | **{result.total_safe}** |")
        lines.append(f"| Total Changes | **{len(result.changes)}** |")
        lines.append("")

        if result.is_compatible:
            lines.append("> **Schema is compatible.** No breaking changes detected.")
        else:
            lines.append(
                f"> **Schema is NOT compatible.** "
                f"{result.total_breaking} breaking change(s) detected."
            )
        lines.append("")

        if not result.changes:
            lines.append("_No schema changes detected._")
            return "\n".join(lines)

        # Alterações por tabela
        lines.append("### Changes by Table")
        lines.append("")

        changes_by_table = result.changes_by_table()

        for table_key, changes in changes_by_table.items():
            breaking = [c for c in changes if c.severity == Severity.BREAKING]
            warnings = [c for c in changes if c.severity == Severity.WARNING]
            safe = [c for c in changes if c.severity == Severity.SAFE]

            badges = []
            if breaking:
                badges.append(f" {len(breaking)} breaking")
            if warnings:
                badges.append(f" {len(warnings)} warning")
            if safe:
                badges.append(f" {len(safe)} safe")

            lines.append(f"#### `{table_key}` — {' · '.join(badges)}")
            lines.append("")
            lines.append("| Severity | Column | Change Type | Before | After |")
            lines.append("|----------|--------|-------------|--------|-------|")

            for change in changes:
                emoji = _SEVERITY_EMOJI.get(change.severity, "⚪")
                label = _SEVERITY_LABEL.get(change.severity, change.severity.value)
                col = f"`{change.column_name}`" if change.column_name else "—"
                old_val = f"`{change.old_value}`" if change.old_value is not None else "—"
                new_val = f"`{change.new_value}`" if change.new_value is not None else "—"
                lines.append(
                    f"| {emoji} {label} | {col} | {change.change_type.value} "
                    f"| {old_val} | {new_val} |"
                )

            lines.append("")

            # Sugestões
            suggestions = [c.suggestion for c in changes if c.suggestion]
            if suggestions:
                lines.append("**Suggestions:**")
                for suggestion in suggestions:
                    lines.append(f"- {suggestion}")
                lines.append("")

        lines.append("---")
        lines.append("_Generated by [DriftBrake](https://github.com/yurivski/driftbrake)_")

        return "\n".join(lines)

    def write(self, result: DiffResult) -> None:
        # Grava o relatório Markdown no disco.
        if self.output_path is None:
            raise ValueError("output_path must be set to write to a file.")
        content = self.render(result)
        self.output_path.parent.mkdir(parents=True, exist_ok=True)
        self.output_path.write_text(content, encoding="utf-8")

    def to_string(self, result: DiffResult) -> str:
        # Retorna o relatório Markdown como string."""
        return self.render(result)
