from typing import Protocol, runtime_checkable


@runtime_checkable
class Reporter(Protocol):
    """Saída visual / observabilidade. Sem retorno — apenas efeito colateral."""

    def on_no_drift(self, result) -> None: ...
    def on_safe(self, result) -> None: ...
    def on_warning(self, result) -> None: ...
    def on_breaking(self, result) -> None: ...
    def on_contract_missing(self, contract_path: str) -> None: ...
    def on_contract_created(self, contract_path: str) -> None: ...
    def on_released(self) -> None: ...
    def on_blocked(self, reason: str) -> None: ...


@runtime_checkable
class Prompter(Protocol):
    """Decisões interativas. Retorna bool (True = prosseguir)."""

    def confirm_create_contract(self, contract_path: str) -> bool: ...
    def confirm_continue_with_warnings(self, result) -> bool: ...
    def confirm_continue_with_safe(self, result) -> bool: ...
